title: "scottc.me"
email: ""
description: "-"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scottc.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  scottcunningham
linkedin_username: scott-cunningham-13552872

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
